#!/usr/bin/env bash

if [[ $1 == "-h" ]];then
    ./build-webkit --help 2>&1 | grep -i "droid"
    exit 1
fi

_print() {
    RED='\033[0;31m'
    NC='\033[0m' 
    echo -e "${RED}$1${NC}"
}

if [[ $# == 0 ]];then
    echo "# Build [Release]"    
else
    echo "# Build [$@]"
fi

_log="build.log"
_err="error.log"

./build-webkit --droid $@ 2> ${_log}

if [[ $! != 0 && `stat -c%s ${_err}` != 0 ]];then
    _print "# Error ------------------------------------------------"
    cat ${_log} | grep "error:" > ${_err}
    tail -10 ${_err}
    _print "# Check all error messages in ${_err}"
    rm ${_log}
fi
